Error on incorrect instance name

diff --git a/scripts/ec2auth b/scripts/ec2auth
--- a/scripts/ec2auth
+++ b/scripts/ec2auth
@@ -15,11 +15,12 @@
 [ "$#" -ne 1 ] && echo "Usage: ec2auth <instance>" && exit 1
 
 set -e
-echo "Setting inbound SSH for ec2..."
 
 DIR="$(cd "$(dirname "$0")" && pwd )"
 INSTANCE_ID="$(awk "/$1/"'{ print $2 }' "$DIR/instances")"
 PREV_IP="$(awk "/$1/"'{ print $3 }' "$DIR/instances")"
+
+[ -z $INSTANCE_ID ] && echo "Error: <instance> must exist in your instances file" && exit 1
 
 MY_IP="$(dig +short myip.opendns.com @resolver1.opendns.com)"
 
@@ -27,6 +28,7 @@ GROUP_ID="$(aws ec2 describe-instance-attribute \
     --instance-id "$INSTANCE_ID" --attribute groupSet \
     | awk '/GROUPS/ { print $2 }')"
 
+echo "Setting inbound SSH for $1"
 aws ec2 revoke-security-group-ingress --group-id $GROUP_ID --protocol tcp --port 22 --cidr $PREV_IP
 aws ec2 authorize-security-group-ingress --group-id $GROUP_ID --protocol tcp --port 22 --cidr $MY_IP/32 
 
